spring.application.name=AgriTrack

server.port=8080

spring.datasource.url=jdbc:sqlserver://103.91.218.117:1922;databaseName=Student;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Saavir@1922
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true

# Increase max upload size
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

jwt.secret=Y^n29@GqR!x8Mpl!4s*V1dZ#A9wE6cTf

# Cloudinary credentials
cloudinary.cloud_name=dkaptdpr1
cloudinary.api_key=963686279311261
cloudinary.api_secret=s0tqMaQfw4mSixJKWq5zQoQ9F1Q


