package AgriTrackBackend.INVOICE;

import AgriTrackBackend.AUDIT.AuditAction;
import AgriTrackBackend.AUDIT.AuditService;
import AgriTrackBackend.COMMON.PageResponse;
import AgriTrackBackend.COMMON.PaginationUtil;
import AgriTrackBackend.CUSTOMER.Customer;
import AgriTrackBackend.CUSTOMER.CustomerRepository;
import AgriTrackBackend.EXCEPTION.ForbiddenException;
import AgriTrackBackend.EXCEPTION.ResourceNotFoundException;
import AgriTrackBackend.SECURITY.CurrentUser;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Service
public class InvoiceService {

    @Autowired
    private InvoiceRepository repository;

    @Autowired
    private CustomerRepository customerRepository;

    @Autowired
    private AuditService auditService;

    @Transactional
    public Invoice save(Invoice invoice) {
        // ✅ invoices are always generated by the owner for one of their customers
        invoice.setOwnerId(CurrentUser.id());
        if (invoice.getInvoiceDate() == null) {
            invoice.setInvoiceDate(LocalDate.now());
        }
        if (invoice.getInvoiceNumber() == null) {
            invoice.setInvoiceNumber(generateInvoiceNumber());
        }
        invoice.setTotalAmount(computeTotal(invoice));
        if (invoice.getStatus() == null) {
            invoice.setStatus("UNPAID");
        }
        Invoice saved = repository.saveAndFlush(invoice);
        auditService.log(AuditAction.CREATE, "Invoice", saved.getInvoiceId(), null, saved);
        return saved;
    }

    private BigDecimal computeTotal(Invoice inv) {
        BigDecimal total = nz(inv.getSubtotal())
                .add(nz(inv.getExtraCharges()))
                .add(nz(inv.getTax()));
        return total;
    }

    private BigDecimal nz(BigDecimal v) {
        return v == null ? BigDecimal.ZERO : v;
    }

    private String generateInvoiceNumber() {
        return "INV-" + System.currentTimeMillis();
    }

    public List<Invoice> getAll() {
        return repository.findAll();
    }

    public List<Invoice> getByOwner(Long ownerId) {
        CurrentUser.requireSelf(ownerId);
        return repository.findByOwnerIdOrderByInvoiceIdDesc(ownerId);
    }

    public PageResponse<Invoice> searchPaged(Long ownerId, String search, String status,
                                              LocalDate from, LocalDate to,
                                              Integer page, Integer size, String sortBy, String sortDir) {
        CurrentUser.requireSelf(ownerId);
        Pageable pageable = PaginationUtil.build(page, size, sortBy, sortDir, "createdAt");
        String s = (search == null || search.isBlank()) ? null : search;
        String st = (status == null || status.isBlank()) ? null : status;
        return PageResponse.of(repository.search(ownerId, s, st, from, to, pageable));
    }

    public List<Invoice> getByCustomer(Long customerId) {
        assertCustomerAccess(customerId);
        return repository.findByCustomerIdOrderByInvoiceIdDesc(customerId);
    }

    // owner of the customer, or the customer's own linked login
    private void assertCustomerAccess(Long customerId) {
        Customer customer = customerRepository.findById(customerId)
                .orElseThrow(() -> new ResourceNotFoundException("Customer not found with id: " + customerId));
        Long me = CurrentUser.id();
        boolean allowed = (customer.getOwnerId() != null && customer.getOwnerId().equals(me))
                || (customer.getUserId() != null && customer.getUserId().equals(me));
        if (!allowed) {
            throw new ForbiddenException("You do not have access to this customer's invoices");
        }
    }

    public Invoice getById(Long id) {
        Invoice invoice = repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Invoice not found with id: " + id));
        assertAccess(invoice);
        return invoice;
    }

    // the issuing owner, or the customer it was billed to
    private void assertAccess(Invoice invoice) {
        Long me = CurrentUser.id();
        if (invoice.getOwnerId() != null && invoice.getOwnerId().equals(me)) return;
        if (invoice.getCustomerId() != null) {
            Customer customer = customerRepository.findById(invoice.getCustomerId()).orElse(null);
            if (customer != null && customer.getUserId() != null && customer.getUserId().equals(me)) return;
        }
        throw new ForbiddenException("You do not have access to this invoice");
    }

    private void assertOwner(Invoice invoice) {
        if (invoice.getOwnerId() == null || !invoice.getOwnerId().equals(CurrentUser.id())) {
            throw new ForbiddenException("Only the issuing owner can modify this invoice");
        }
    }

    @Transactional
    public Invoice update(Long id, Invoice data) {
        Invoice existing = getById(id);
        assertOwner(existing);
        String before = auditService.snapshot(existing);
        existing.setCustomerId(data.getCustomerId());
        existing.setWorkId(data.getWorkId());
        existing.setBookingId(data.getBookingId());
        existing.setSubtotal(data.getSubtotal());
        existing.setExtraCharges(data.getExtraCharges());
        existing.setTax(data.getTax());
        existing.setStatus(data.getStatus());
        existing.setPdfUrl(data.getPdfUrl());
        existing.setNotes(data.getNotes());
        existing.setTotalAmount(computeTotal(existing));
        Invoice saved = repository.saveAndFlush(existing);
        auditService.logRaw(AuditAction.UPDATE, "Invoice", id, before, saved);
        return saved;
    }

    @Transactional
    public Invoice updateStatus(Long id, String status) {
        Invoice existing = getById(id);
        assertOwner(existing);
        String before = auditService.snapshot(existing);
        existing.setStatus(status);
        Invoice saved = repository.saveAndFlush(existing);
        auditService.logRaw(AuditAction.STATUS_CHANGE, "Invoice", id, before, saved);
        return saved;
    }

    @Transactional
    public void deleteById(Long id) {
        Invoice existing = getById(id);
        assertOwner(existing);
        String before = auditService.snapshot(existing);
        repository.delete(existing);
        auditService.logRaw(AuditAction.DELETE, "Invoice", id, before, null);
    }
}
