package AgriTrackBackend.INVOICE;

import AgriTrackBackend.COMMON.PageResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;

@RestController
@RequestMapping("/api/v1/invoice")
@CrossOrigin
@Tag(name = "Invoices", description = "Invoices generated by an owner for a customer/booking. Accessible by the issuing owner or the billed customer.")
public class InvoiceController {

    @Autowired
    private InvoiceService service;

    @Operation(summary = "Create an invoice", description = "ownerId is always taken from the caller's JWT.")
    @PostMapping("/create")
    public Invoice create(@RequestBody Invoice invoice) {
        return service.save(invoice);
    }

    @GetMapping("/getAll")
    public List<Invoice> getAll() {
        return service.getAll();
    }

    @GetMapping("/getByOwner/{ownerId}")
    public List<Invoice> getByOwner(@PathVariable Long ownerId) {
        return service.getByOwner(ownerId);
    }

    @Operation(summary = "Paged/search/filter/sort invoice list", description = "?search matches invoice number/notes; ?status/?from/?to filter exactly. Additive.")
    @GetMapping("/search-paged/{ownerId}")
    public PageResponse<Invoice> searchPaged(
            @PathVariable Long ownerId,
            @RequestParam(required = false) String search,
            @RequestParam(required = false) String status,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate from,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate to,
            @RequestParam(required = false) Integer page,
            @RequestParam(required = false) Integer size,
            @RequestParam(required = false) String sortBy,
            @RequestParam(required = false) String sortDir
    ) {
        return service.searchPaged(ownerId, search, status, from, to, page, size, sortBy, sortDir);
    }

    @GetMapping("/getByCustomer/{customerId}")
    public List<Invoice> getByCustomer(@PathVariable Long customerId) {
        return service.getByCustomer(customerId);
    }

    @GetMapping("/getById/{id}")
    public Invoice getById(@PathVariable Long id) {
        return service.getById(id);
    }

    @Operation(summary = "Update an invoice", description = "Only the issuing owner may update (403 otherwise).")
    @PutMapping("/update/{id}")
    public Invoice update(@PathVariable Long id, @RequestBody Invoice invoice) {
        return service.update(id, invoice);
    }

    @Operation(summary = "Update invoice status", description = "e.g. UNPAID -> PAID. Only the issuing owner may update.")
    @PutMapping("/status/{id}")
    public Invoice updateStatus(@PathVariable Long id, @RequestParam String status) {
        return service.updateStatus(id, status);
    }

    @Operation(summary = "Delete an invoice", description = "Only the issuing owner may delete (403 otherwise).")
    @DeleteMapping("/deleteById/{id}")
    public String deleteById(@PathVariable Long id) {
        service.deleteById(id);
        return "Invoice deleted successfully";
    }
}
