-- Enterprise-grade authentication: device sessions + login history.
-- Existing schema was created manually (ddl-auto=none); Flyway is being
-- introduced starting from this migration and is baselined at version 0
-- (see spring.flyway.baseline-* in application.properties) so it does not
-- attempt to recreate any pre-existing tables.

CREATE TABLE USER_SESSIONS (
    ID                  BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_ID             BIGINT NOT NULL,
    REFRESH_TOKEN_HASH  VARCHAR(128) NOT NULL,
    DEVICE_ID           VARCHAR(255) NULL,
    DEVICE_NAME         VARCHAR(255) NULL,
    PLATFORM            VARCHAR(50)  NULL,
    APP_VERSION         VARCHAR(50)  NULL,
    IP_ADDRESS          VARCHAR(64)  NULL,
    LOGIN_TIME          DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LAST_ACTIVITY       DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    EXPIRES_AT          DATETIME2 NOT NULL,
    REVOKED             BIT NOT NULL DEFAULT 0,
    LOGOUT_TIME         DATETIME2 NULL,
    CONSTRAINT FK_USER_SESSIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT UQ_USER_SESSIONS_REFRESH_HASH UNIQUE (REFRESH_TOKEN_HASH)
);

CREATE INDEX IX_USER_SESSIONS_USER_ID ON USER_SESSIONS (USER_ID);
CREATE INDEX IX_USER_SESSIONS_USER_REVOKED ON USER_SESSIONS (USER_ID, REVOKED);

CREATE TABLE LOGIN_HISTORY (
    ID              BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_ID         BIGINT NULL,
    LOGIN_TIME      DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    LOGOUT_TIME     DATETIME2 NULL,
    IP_ADDRESS      VARCHAR(64) NULL,
    DEVICE          VARCHAR(255) NULL,
    PLATFORM        VARCHAR(50) NULL,
    STATUS          VARCHAR(20) NOT NULL,
    FAILURE_REASON  VARCHAR(255) NULL,
    CONSTRAINT FK_LOGIN_HISTORY_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE INDEX IX_LOGIN_HISTORY_USER_ID ON LOGIN_HISTORY (USER_ID);
