-- Driver attendance (clock in/out, break, leave, overtime) and monthly
-- payroll (salary calculation, incentives, penalties). Extends the existing
-- DRIVERS table with a base monthly salary rather than duplicating driver data.

ALTER TABLE DRIVERS ADD MONTHLY_SALARY DECIMAL(12,2) NULL;

CREATE TABLE DRIVER_ATTENDANCE (
    ATTENDANCE_ID   BIGINT IDENTITY(1,1) PRIMARY KEY,
    DRIVER_ID       BIGINT NOT NULL,
    OWNER_ID        BIGINT NOT NULL,
    ATTENDANCE_DATE DATE   NOT NULL,
    CLOCK_IN_TIME   DATETIME2 NULL,
    CLOCK_OUT_TIME  DATETIME2 NULL,
    BREAK_MINUTES   INT NOT NULL DEFAULT 0,
    OVERTIME_MINUTES INT NOT NULL DEFAULT 0,
    -- PRESENT / ABSENT / LEAVE / HALF_DAY
    STATUS          VARCHAR(20) NOT NULL DEFAULT 'PRESENT',
    LEAVE_REASON    VARCHAR(255) NULL,
    NOTES           VARCHAR(500) NULL,
    CREATED_AT      DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_ATTENDANCE_DRIVER FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(DRIVER_ID),
    CONSTRAINT UQ_ATTENDANCE_DRIVER_DATE UNIQUE (DRIVER_ID, ATTENDANCE_DATE)
);

CREATE INDEX IX_ATTENDANCE_OWNER ON DRIVER_ATTENDANCE (OWNER_ID, ATTENDANCE_DATE);
CREATE INDEX IX_ATTENDANCE_DRIVER ON DRIVER_ATTENDANCE (DRIVER_ID, ATTENDANCE_DATE);

CREATE TABLE DRIVER_PAYROLL (
    PAYROLL_ID      BIGINT IDENTITY(1,1) PRIMARY KEY,
    DRIVER_ID       BIGINT NOT NULL,
    OWNER_ID        BIGINT NOT NULL,
    PAYROLL_MONTH   VARCHAR(7) NOT NULL, -- "yyyy-MM"
    BASE_SALARY     DECIMAL(12,2) NOT NULL DEFAULT 0,
    PRESENT_DAYS    INT NOT NULL DEFAULT 0,
    ABSENT_DAYS     INT NOT NULL DEFAULT 0,
    LEAVE_DAYS      INT NOT NULL DEFAULT 0,
    OVERTIME_MINUTES INT NOT NULL DEFAULT 0,
    OVERTIME_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0,
    INCENTIVES      DECIMAL(12,2) NOT NULL DEFAULT 0,
    PENALTIES       DECIMAL(12,2) NOT NULL DEFAULT 0,
    NET_SALARY      DECIMAL(12,2) NOT NULL DEFAULT 0,
    -- PENDING / PAID
    STATUS          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    PAID_DATE       DATETIME2 NULL,
    NOTES           VARCHAR(500) NULL,
    CREATED_AT      DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_PAYROLL_DRIVER FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(DRIVER_ID),
    CONSTRAINT UQ_PAYROLL_DRIVER_MONTH UNIQUE (DRIVER_ID, PAYROLL_MONTH)
);

CREATE INDEX IX_PAYROLL_OWNER ON DRIVER_PAYROLL (OWNER_ID, PAYROLL_MONTH);
