-- RC / Insurance / Permit / PUC / Fitness documents for a tractor, with
-- expiry tracking so renewal reminders can be generated automatically.

CREATE TABLE TRACTOR_DOCUMENTS (
    DOCUMENT_ID     BIGINT IDENTITY(1,1) PRIMARY KEY,
    TRACTOR_ID      BIGINT NOT NULL,
    OWNER_ID        BIGINT NOT NULL,
    -- RC / INSURANCE / PERMIT / PUC / FITNESS
    DOCUMENT_TYPE   VARCHAR(20) NOT NULL,
    DOCUMENT_NUMBER VARCHAR(100) NULL,
    FILE_URL        VARCHAR(500) NOT NULL,
    ISSUE_DATE      DATE NULL,
    EXPIRY_DATE     DATE NULL,
    REMINDER_SENT   BIT NOT NULL DEFAULT 0,
    NOTES           VARCHAR(500) NULL,
    CREATED_AT      DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_TRACTOR_DOCUMENTS_TRACTOR FOREIGN KEY (TRACTOR_ID) REFERENCES TRACTORS(TRACTOR_ID),
    CONSTRAINT UQ_TRACTOR_DOCUMENT_TYPE UNIQUE (TRACTOR_ID, DOCUMENT_TYPE)
);

CREATE INDEX IX_TRACTOR_DOCUMENTS_OWNER ON TRACTOR_DOCUMENTS (OWNER_ID);
CREATE INDEX IX_TRACTOR_DOCUMENTS_EXPIRY ON TRACTOR_DOCUMENTS (EXPIRY_DATE, REMINDER_SENT);
