-- Per-user, per-notification-type channel preferences. PUSH and IN_APP are
-- live channels today; SMS and EMAIL columns are provisioned now so the
-- schema doesn't need to change when those channels are wired up, but they
-- default to disabled since no SMS/Email sender exists yet.

CREATE TABLE NOTIFICATION_PREFERENCES (
    PREFERENCE_ID     BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_ID           BIGINT NOT NULL,
    -- BOOKING / PAYMENT / DOCUMENT_EXPIRY / RATE_ALERT / MAINTENANCE / PAYROLL / CHAT / GENERAL
    NOTIFICATION_TYPE VARCHAR(30) NOT NULL,
    PUSH_ENABLED      BIT NOT NULL DEFAULT 1,
    IN_APP_ENABLED    BIT NOT NULL DEFAULT 1,
    SMS_ENABLED       BIT NOT NULL DEFAULT 0,
    EMAIL_ENABLED     BIT NOT NULL DEFAULT 0,
    CREATED_AT        DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT        DATETIME2 NULL,
    CONSTRAINT UQ_NOTIFICATION_PREFERENCE UNIQUE (USER_ID, NOTIFICATION_TYPE)
);

CREATE INDEX IX_NOTIFICATION_PREFERENCES_USER ON NOTIFICATION_PREFERENCES (USER_ID);
